title: BZHista ☕️
email: your-email@example.com
description: >-
  Blog personnel où je parle de café.
url: "http://bzhista.frad.in"

theme: jekyll-theme-merlot

github:
  is_project_page: false

plugins:
  - liquid_reading_time
  - liquid_pluralize
